default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_db

test:
  <<: *default
  database: my_db_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"]%>